<script lang="ts">
    import ModList from '$lib/components/ModList.svelte';
    import { ModManager } from '$lib/mods';
    import { onMount } from 'svelte';
    import * as saf from '../../src-tauri/plugins/saf/guest-js/index.ts';

    const manager = new ModManager();
    let mods = $state(manager.getMods());
    let configUri = $state("");
    let status = $state("");
    let error = $state("");
    let permissionGranted = $state(false);

    onMount(async () => {
        try {
            status = "Checking permissions...";
            const storedUri = localStorage.getItem("openmw_config_uri");
            if (storedUri) {
                configUri = storedUri;
                permissionGranted = await saf.checkPermission(configUri);
            }

            if (permissionGranted) {
                await loadConfig();
            } else {
                status = "Permission required to access OpenMW configuration.";
            }
        } catch (e: any) {
            error = "Initialization failed: " + (e.message || e);
            status = "";
        }
    });

    async function loadConfig() {
        if (!configUri) return;
        try {
            status = "Loading config...";
            const content = await saf.readFile(configUri);
            // Parse config and populate manager (omitted for brevity)
            status = "Config loaded";
            
            // Sample mods for UI demonstration if nothing loaded
            if (mods.length === 0) {
                manager.addMod({ name: 'Morrowind.esm', enabled: true });
                manager.addMod({ name: 'Tribunal.esm', enabled: true });
                manager.addMod({ name: 'Bloodmoon.esm', enabled: true });
                mods = [...manager.getMods()];
            }
        } catch (e: any) {
            error = "Failed to load config: " + (e.message || e);
            status = "";
        }
    }

    async function handleRequestPermission() {
        try {
            status = "Requesting permission...";
            const uri = await saf.requestPermission();
            configUri = uri;
            localStorage.setItem("openmw_config_uri", uri);
            permissionGranted = true;
            status = "Permission granted";
            await loadConfig();
        } catch (e: any) {
            error = "Permission request failed: " + (e.message || e);
            status = "";
        }
    }

    function handleToggle(name: string) {
        manager.toggleMod(name);
        mods = [...manager.getMods()];
    }

    function handleReorder(from: number, to: number) {
        manager.reorder(from, to);
        mods = [...manager.getMods()];
    }

    async function handleSave() {
        if (!permissionGranted || !configUri) {
            error = "Permission not granted";
            return;
        }
        try {
            status = "Saving...";
            error = "";
            const content = "# Generated by OMM\n" + mods.map(m => `content=${m.name}`).join("\n");
            await saf.writeFile(configUri, content);
            status = "Save successful";
        } catch (e: any) {
            error = "Save failed: " + (e.message || e);
            status = "";
        }
    }
</script>

<main class="container mx-auto p-4 max-w-2xl">
    <h1 class="text-3xl font-bold text-center border-b mb-6 pb-2">OpenMW Android Modloader</h1>
    
    <div class="mb-6 bg-white p-4 rounded-lg border shadow-sm gap-4">
        {#if !permissionGranted}
            <div class="flex flex-col items-center py-4">
                <p class="text-sm text-gray-600 mb-4 text-center">
                    To manage your mods, please grant permission to access the OpenMW configuration directory.
                </p>
                <button 
                    class="bg-green-600 hover:bg-green-700 text-white font-semibold px-8 py-3 rounded-lg shadow-md transition-all active:scale-95"
                    onclick={handleRequestPermission}
                >
                    Grant Permission
                </button>
            </div>
        {:else}
            <div class="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
                <div class="overflow-hidden w-full">
                    <p class="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Selected URI</p>
                    <p class="text-sm font-mono truncate text-gray-700 bg-gray-50 p-1 rounded border" title={configUri}>{configUri}</p>
                </div>
                <button 
                    class="w-full md:w-auto bg-blue-600 hover:bg-blue-700 text-white font-semibold px-6 py-2 rounded-lg shadow-md transition-all active:scale-95"
                    onclick={handleSave}
                >
                    Save Changes
                </button>
            </div>
        {/if}
    </div>

    {#if error}
        <div class="mb-6 p-4 bg-red-50 border-l-4 border-red-500 text-red-700 rounded shadow-sm">
            <div class="flex items-center">
                <span class="font-bold mr-2">Error:</span>
                <span>{error}</span>
            </div>
        </div>
    {/if}

    {#if status}
        <p class="text-center text-sm mb-6 text-gray-500 animate-pulse">{status}</p>
    {/if}

    <div class="bg-white rounded-lg border shadow-sm overflow-hidden">
        <ModList {mods} onToggle={handleToggle} onReorder={handleReorder} />
    </div>
</main>